const A=document.getElementById('app'); let subjects=[],me=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(url,opt={}){let r=await fetch(url,opt);let d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d}
function login(){A.innerHTML=`<div class="login"><div class="brand">Study <span>Lab</span></div><h2>Private Learning Portal</h2><p class="muted">Sign in to access your classes and materials.</p><form onsubmit="doLogin(event)"><input class="field" name="username" placeholder="Username" required><input class="field" name="password" type="password" placeholder="Password" required><button class="btn" style="width:100%">Sign in</button></form><p class="small muted">Admin access is configured by the site owner.</p></div>`}
async function doLogin(e){e.preventDefault();try{me=await api('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});render()}catch(x){alert(x.message)}}
async function render(){subjects=await api('/api/subjects'); if(!me){login();return} let anns=await api('/api/announcements'), mats=await api('/api/materials'); A.innerHTML=`<header class="top"><div class="brand">Study <span>Lab</span></div><div class="nav"><span class="pill">${esc(me.role==='admin'?'Admin':'Student')}</span><button class="btn alt" onclick="logout()">Logout</button></div></header><main class="wrap"><section class="hero"><span class="pill">Learning Dashboard</span><h1>Learn. Practice. Build.</h1><p class="muted">Your private academic workspace for theory, labs, notes, and class updates.</p></section><h2>My Subjects</h2><div class="grid">${subjects.map((s,i)=>`<div class="card subject"><div class="icon">${['⚡','🔌','📘','🧪','💻','🖥️'][i]}</div><h3>${esc(s.name)}</h3><p class="muted small">Announcements, classes and study materials</p><button class="btn alt" onclick="filterSub(${s.id})">View materials</button></div>`).join('')}</div><section class="section"><div class="row"><h2>Latest Announcements</h2>${me.role==='admin'?'<button class="btn" onclick="adminPanel()">Admin Panel</button>':''}</div><div id="anns">${anns.length?anns.map(a=>`<div class="card notice"><b>${esc(a.title)}</b><div class="small muted">${esc(a.subject)} · ${esc(a.created_at)}</div><p>${esc(a.body)}</p>${me.role==='admin'?`<button class="btn danger small" onclick="del('/api/announcements/${a.id}')">Delete</button>`:''}</div>`).join(''):'<p class="muted">No announcements yet.</p>'}</div></section><section class="section"><h2>Study Materials</h2><div class="grid">${mats.length?mats.map(m=>`<div class="card"><span class="pill">${esc(m.type)}</span><h3>${esc(m.title)}</h3><p class="small muted">${esc(m.subject)}</p>${m.url?`<a class="btn" href="${esc(m.url)}" target="_blank">Open</a>`:''} ${me.role==='admin'?`<button class="btn danger small" onclick="del('/api/materials/${m.id}')">Delete</button>`:''}</div>`).join(''):'<p class="muted">No materials uploaded yet.</p>'}</div></section></main>`}
async function filterSub(id){let [a,m]=await Promise.all([api('/api/announcements'),api('/api/materials')]);let s=subjects.find(x=>x.id===id);let aa=a.filter(x=>x.subject_id===id),mm=m.filter(x=>x.subject_id===id);alert(`${s.name}\n\nAnnouncements: ${aa.length}\nMaterials: ${mm.length}\n\nUse the dashboard below to open available resources.`)}
async function adminPanel(){A.insertAdjacentHTML('beforeend',`<div class="wrap"><div class="card"><h2>Admin Panel</h2><h3>New Announcement</h3><form onsubmit="addAnn(event)"><select class="field" name="subject_id">${subjects.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select><input class="field" name="title" placeholder="Title" required><textarea class="field" name="body" placeholder="Announcement" required></textarea><button class="btn">Publish</button></form><h3>Upload Material</h3><form onsubmit="addMat(event)"><select class="field" name="subject_id">${subjects.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select><input class="field" name="title" placeholder="Material title" required><select class="field" name="type"><option>PDF</option><option>Notes</option><option>Class Link</option></select><input class="field" name="url" placeholder="Class/material URL (optional)"><input class="field" type="file" name="file"><button class="btn">Add Material</button></form></div></div>`)}
async function addAnn(e){e.preventDefault();await api('/api/announcements',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});render()} async function addMat(e){e.preventDefault();await api('/api/materials',{method:'POST',body:new FormData(e.target)});render()} async function del(u){await api(u,{method:'DELETE'});render()} async function logout(){await api('/api/logout',{method:'POST'});me=null;login()}
(async()=>{try{me=await api('/api/me')}catch{} render()})();
